### ISSUE TITLE
can we get start without docker

### ISSUE THREAD

**Issue by SeekPoint** [tzano/wren#1]

**Comment by tzano** [comment]
Yes, you need to install install Kafka, mongodb and the [required packages](https://github.com/tzano/wren/blob/master/docker/wren_app/requirements.txt) to be able to run the application. However, it's recommended to use a dockerized version [to ease the deployment process. ](https://www.docker.com/what-docker)

**Comment by SeekPoint** [comment]
any readme on how to launch it step by step?
