### ISSUE TITLE
Doesnt build

### ISSUE THREAD

**Issue by liuzzi** [tzano/wren#2]
the project doesnt build with docker, i get this error:

`ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker/docker-compose.yml", line 2, column 3
expected <block end>, but found '<block mapping start>'
  in "./docker/docker-compose.yml", line 47, column 4
Makefile:9: recipe for target 'build' failed
make: *** [build] Error 1
`

also, where can we download the model files  "intent_classifier.pkl",  and  "crf_model.pkl" ?

**Comment by tzano** [comment]
Thanks @liuzzi. I fixed the formatting of docker files.
I will update the models. However, you can always train the model using the same dataset.
